# This file uses GitHub actions to create a release, including an
# installer

name: Prepare release
on:
  release:
    types:
      - created
      
jobs:
  build:
    env:
      PROJECT: XLKitLearn
      APP_ID: YaocNmA99ZWqRnwKgQKZKayRJojMjq
      APP_PUBLISHER: Dynamic Analytics LLC
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      RELEASE_NAME: ${{ github.event.release.name }}
    runs-on: windows-2022
    strategy:
      matrix:
        architecture: ['x86', 'x64'] 
    steps:
    - name: Starting and printing github context for debugging
      run: echo "$GITHUB_CONTEXT"
    - name: Check out repo code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: ${{ matrix.architecture }}
    - name: Run the installer prep
      shell: bash
      run: |
        python .github/workflows/prepare_release.py
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Add the location of the install creator to the path
      shell: bash
      run: echo "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64" >> $GITHUB_PATH
    - name: Create the installer
      run: iscc .github/installer.iss
    - name: Rename the installer to include bitness
      shell: bash
      run: mv .github/Output/${{ env.PROJECT }}.exe .github/Output/${{ env.PROJECT }}-${{ matrix.architecture }}.exe
    - name: Upload files to the GitHub release page
      uses: softprops/action-gh-release@v1
      with:
        files: |
          .github/Output/${{ env.PROJECT }}-${{ matrix.architecture }}.exe
  push_non_windows_files:
    env:
      PROJECT: XLKitLearn
      APP_ID: YaocNmA99ZWqRnwKgQKZKayRJojMjq
      APP_PUBLISHER: Dynamic Analytics LLC
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      RELEASE_NAME: ${{ github.event.release.name }}
    runs-on: windows-2022 
    steps:
    - name: Starting and printing github context for debugging
      run: echo "$GITHUB_CONTEXT"
    - name: Check out repo code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: ${{ matrix.architecture }}
    - name: Run the installer prep
      shell: bash
      run: |
        python .github/workflows/prepare_release.py
    - name: Upload files to the GitHub release page
      uses: softprops/action-gh-release@v1
      with:
        files: |
          XLKitLearn_installer.sh
          version
          XLKitLearn.xltm   