# This file creates a GitHub action to run process_push.py every
# time a commit is pushed to the repo

name: Process push
on:
  push:
    branches:
      # We only want to activate this when a new version is pushed, NOT when
      # a new release is created. We do this by adding this branches filter,
      # as per
      #   https://stackoverflow.com/questions/59906471/why-does-a-release-event-generate-a-push-event-as-well
      - '**'
jobs:
  ProcessPush:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Python packages
        run: |
          pip install oletools
          pip install openpyxl
          pip install pandas
      - name: Process the push
        run: python ./.github/workflows/process_push.py
      - name: Commit
        run: |
          git config --global user.name 'VBA Robot'
          git config --global user.email 'VBA Robot'
          git add .
          git commit -am "VBA Robot" --allow-empty
          git push